name: Prettier

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: format
        uses: creyD/prettier_action@v4.3
