name: Prettier Action

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: format
      - uses: creyD/prettier_action@v4.3
